### ISSUE TITLE
append_weighted_distances bug

### ISSUE THREAD

**Issue by goreaditya** [pbsag/swimctr#11]
@rickdonnelly 
One of the argument accepted by the `append_weighted_distances` function is `ignore_regions`. 
https://github.com/tlumip/swimctr/blob/a4e4ca163b66bd0d6d3d908c66dceaf3373dd757/R/append_weighted_distances.R#L26-L27
The same variable used within the body of the function uses the name `ignored_regions`. This causes the function to fail if there is no global variable named `ignored_regions`. Fix should be to change the argument name to `ignored_regions` in the definition of the function on line 27.
https://github.com/tlumip/swimctr/blob/a4e4ca163b66bd0d6d3d908c66dceaf3373dd757/R/append_weighted_distances.R#L44-L45

**Comment by rickdonnelly** [comment]
Good catch! I've updated the code to consistently use `ignore_regions` throughout and verified that this fix doesn't break running CT.
