### ISSUE TITLE
local_truck_generation() is incompatible with swim small

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/swimctr#2]
Running ct in the swim small causes problems with thresholds.

The defaults don't work because the difference between 4.2 and 5 is greater than what was set. But changing the `max_resampling_threshold` to 100 also is inadequate because if the flow is 0, then the percent error is `NaN`. Maybe a check to only care about threshold if the flow is greater than like 50?

**Comment by rickdonnelly** [comment]
Whatever solution we come up with to solve the more general case of local_truck_generation() crashing, which also affects full model runs, will solve this as well. That is, we will test the fix on both the regular SWIM runs and swim_small before closing that issue.
