### ISSUE TITLE
License

### ISSUE THREAD

**Issue by gregmacfarlane** [pbsag/swimctr#7]
The [`DESCRIPTION`](https://github.com/tlumip/swimctr/blob/master/DESCRIPTION#L15) file says that the license is CC0. The [Creative Commons FAQ](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software) states,

>Can I apply a Creative Commons license to software?
We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed as “open source” by the Open Source Initiative.

>Unlike software-specific licenses, CC licenses do not contain specific terms about the distribution of source code, which is often important to ensuring the free reuse and modifiability of software. Many software licenses also address patent rights, which are important to software but may not be applicable to other copyrightable works. Additionally, our licenses are currently not compatible with the major software licenses, so it would be difficult to integrate CC-licensed work with other free software. Existing software licenses were designed specifically for use with software and offer a similar set of rights to the Creative Commons licenses.

Could @rickdonnelly release swimctr under the [Apache](https://choosealicense.com/licenses/apache-2.0/) or [MIT](https://choosealicense.com/licenses/mit/) license?

**Comment by rickdonnelly** [comment]
I didn't realize that it was set to CC0. I normally set this to "none," which I've just changed this to reflect.
