### ISSUE TITLE
omxr dependencies broken

### ISSUE THREAD

**Issue by rickdonnelly** [pbsag/swimctr#8]
read_skim_matrices.R uses `omxr::read_zmx()` to read skim distance and travel time matrices in ZMX format. The skims are appended to both local and long-distance truck trip records. I cannot find the `omxr` package in GitHub or in my older code, although pretty sure it was a @gregmacfarlane creation. Thus, I need to either chase down or replicate this functionality in order to rebuild this package.

**Comment by gregmacfarlane** [comment]
It's in [`gregmacfarlane/omxr`](https://github.com/gregmacfarlane/omxr/blob/master/R/zmx.R)

**Comment by rickdonnelly** [comment]
I dialed back Greg Macfarlane's [omxr](https://github.com/gregmacfarlane/omxr/blob/8a1d88f21cf82d392c2bd9d90cbeaba8363b29b1/R/zmx.R) to get recover his `gather_matrix` method, which I've now pasted into my `read_skim_matrix` function so that I don't need to keep going back in commit history to find it. So this is nicely resolved.
